### ISSUE TITLE
pass -doxygen flag

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#12]
SWIG 4.0 can parse doxygen comments in the C++ file and pass them on to Python. It even handles LaTex formulas as far as I can see.

Something like this in the CMakeLists.txt (but I didn't check the `if` statement)

```cmake
  if (SWIG_VERSION VERSION_GREATER_OR_EQUAL 4.0.0)
      SET(CMAKE_SWIG_FLAGS -doxygen)
  endif()
```

**Comment by LeRocci** [comment]
fixed in commit a13c147014d475f558362227368039217bbb6d49

**Comment by KrisThielemans** [comment]
I have trouble now due to https://github.com/swig/swig/issues/2070. You don't?

**Comment by KrisThielemans** [comment]
suggested work-around in SIRF https://github.com/SyneRBI/SIRF/issues/1003
