### ISSUE TITLE
probably remove PETAcquisitionModelUsingRayTracingMatrix  from .i

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#14]
As @evgueni-ovtchinnikov added `PETAcquisitionModelUsingRayTracingMatrix` to C++ in https://github.com/SyneRBI/SIRF/commit/6eb1bc497b80f9f6bf45b647bdc2dda29cc22fea, it'll probably need to be removed from `test.i`

**Comment by LeRocci** [comment]
fixed in commit eab4c8ab7d59b941b6857b16b6b04e378e796ef4
