### ISSUE TITLE
try some renaming to be closer to existing SIRF interface

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#15]
There are a few functions/classes that are currently called differently after SWIG compared to SIRF. Examples are
- `my_clone` -> `clone` (can probably just be called like that in the .i)
- `from_array` -> `fill`. Of course, there's a `fill(float)` already, but it looks like SWIG will take care of checking the argument types. You should show this by making your test script call both `fill(1.1)` and `fill(some_ndarray)`. You could even check the generated wrapper if you feel like it. If this works, it would be worth commenting on in the report
- `xSTIR_FBP2DReconstruction` -> `FBP2DReconstructor` I believe (this would need a `%rename`)

**Comment by LeRocci** [comment]
please see commit f8f893598deaeff1aad0af3fd84480cd92892d72
