### ISSUE TITLE
add LICENSE

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#16]
would you still be able to add license info? Ideally you would use the Apache 2.0 license. 

1. create a `LICENSE.txt` file (copy of https://github.com/SyneRBI/SIRF/blob/master/LICENSE.txt without the first paragraph)
2. create a `NOTICE.txt` file (see example https://github.com/SyneRBI/SIRF/blob/master/NOTICE.txt), which in this case I believe should only mention you and me. My copyright is owned by UCL. Yours is probably owned by yourself.

**Comment by LeRocci** [comment]
see commit 4a056a3baa873f4d917e22a59c24dabadc67ae13
