### ISSUE TITLE
make interface more python-like

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#3]
The wrapping works at the moment, but people will expect the objects to act Python-like. For instance
```python
a.items()
# vs Python-style:
len(a)
```
This can be achieved in 2 ways I believe
- using `%rename` to rename `items` into `__len__`
- using `%extend` to add `__len__`. You can see an example of this in https://github.com/UCL/STIR/blob/master/src/swig/stir.i#L889-L908

Next step would be to do some arithmetic operations:
```python 
 a.multiply(b,c)
 #vs Python-style:
 a = b*c
```
Similarly, you can try something like
- using `%rename` to rename `multiply` to `operator*`
- using `%extend` to add `operator*`.

Some (not so easy) doc on this is http://swig.sourceforge.net/Doc4.0/Python.html#Python_builtin_overloads

I think the `%rename` options are probably best.

**Comment by LeRocci** [comment]
fixed in commit of "%rename branch"
