### ISSUE TITLE
add lines to CMake to install Python files

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#4]
we need to be able to copy the files after building to a particular location. You can probably just copy the following lines from STIR
https://github.com/UCL/STIR/blob/40545147179fbe2b1131679672375cc91a39ab55/src/swig/CMakeLists.txt#L116-L118
obviously adjusting the name (stir) to your project.

After inserting those, if you run CMake, you should have a PYTHON_DEST variable in the list of things that you can set. You can then set it to where you want it. As it's a CACHED variable, it will remember what you set for next time, such that you have to do this only once.

**Comment by LeRocci** [comment]
Fixed in commit 2021/8/9
