### ISSUE TITLE
allow using SIRF files in different places

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#5]
you should be able to use SIRF include files that are located elsewhere. At present you specify `include_directories` as being in the current directory (where the source is). https://github.com/LeRocci/SIRFPROJECT/blob/d4eb8008f051518984616958b689fa95e472dbec/CMakeLists.txt#L23
You can add other directories as well. You could do something like

```cmake
set(SIRF_SOURCE "${CMAKE_SOURCE_DIR}" CACHE PATH "Location of the SIRF source")
include_directories(${SIRF_SOURCE}/src/common/include/)
```
and whatever you need.

At some point, you will be using an installed SIRF, in which case all SIRF include files will be in one location, but you can then just modify the above accordingly.

**Comment by LeRocci** [comment]
Fixed in commit 2021/8/9
