### ISSUE TITLE
adjust wrapping for std:: classes

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#6]
Like the std_string.i, you probably will need to add a few others, maybe only std_vector.i and std_shared_ptr.i, see
http://www.swig.org/Doc4.0/Library.html#Library_stl_cpp_library

In particular, the `shared_ptr` will be important. This is a bit more work than just including that file, see
http://www.swig.org/Doc4.0/Library.html#Library_std_shared_ptr
essentially
```
%include <std_shared_ptr.i>
%shared_ptr(sirf::DataContainer)
%shared_ptr(sirf::ImageData)
Etc
%include "sirf/common/DataContainer.h"
Etc
```

**Comment by LeRocci** [comment]
fixed in commit 43ec52874acbf0ad4c172816b683a5c82e8e63ae
