### ISSUE TITLE
handle clone()

### ISSUE THREAD

**Issue by KrisThielemans** [LeRocci/SIRFPROJECT#7]
As `clone()` returns a `std::unique_ptr`, which SWIG cannot handle yet, we have to work-around it.

A first step could be like
```
%ignore *::clone()
%extend sirf::DataContainer
{
  DataContainer * my_clone() const
  { 
    return clone().get();
  }
}

%newobject *::my_clone();
```

**Comment by evgueni-ovtchinnikov** [comment]
@KrisThielemans does not look good to me, I am afraid.

My understanding is: `clone()` is going to create a clone of `*this` and return its `unique_ptr`, which is going to be destroyed on return from `my_clone()`, which will destroy the clone as its `unique_ptr` owns it.

Should `my_clone` not rather return `shared_ptr<DataContainer>(clone())`?

**Comment by KrisThielemans** [comment]
this is true, except that SWIG handles memory management (because of the `newobject`). However, if it works with `shared_ptr`, I don't mind either way.
