### ISSUE TITLE
FBP2D reconstruction

### ISSUE THREAD

**Issue by evgueni-ovtchinnikov** [LeRocci/SIRFPROJECT#8]
Lines 57 to 66 from `...\sources\SIRF\examples\Python\PET\fbp2d_reconstruction.py` can be used as a starting point with FBP2D reconstruction script.

**Comment by LeRocci** [comment]
Still got the image.write issue

**Comment by LeRocci** [comment]
fixed in commit 1d25e07e9a90e346bd7c559de246feac2fe37751
